--bai8
--1. Thêm dữ liệu vào bảng PROJECTS.
SELECT *FROM PROJECT_KANZY
INSERT INTO PROJECT_KANZY (PROJID, P_DESC,P_END_DATE,P_START_DATE,BUDGET_AMOUNT,MAX_NO_STAFF )
VALUES (1, 'WRITE C030 ', '07-JAN-88','02-JAN-88 ',500,1)
INSERT INTO PROJECT_KANZY (PROJID, P_DESC,P_END_DATE,P_START_DATE,BUDGET_AMOUNT,MAX_NO_STAFF )
VALUES(2, 'PROOF READ NOTES','10-JAN-89', '01-JAN-89 ',600,1);
--2Thêm dữ liệu vào bảng ASSIGNMENTS.
SELECT *FROM ASSIGNMENTS_KANZY
INSERT INTO ASSIGNMENTS_KANZY(PROJID, EMPNO, A_END_DATE,A_START_DATE,BILL_RATE,ASSIGN_TYPE,HOURS)
VALUES(1,7369,'01-JAN-88','03-JAN-88',50.00,'WR',15)
INSERT INTO ASSIGNMENTS_KANZY(PROJID, EMPNO, A_END_DATE,A_START_DATE,BILL_RATE,ASSIGN_TYPE,HOURS)
VALUES(1,7902,'04-JAN-88','07-JAN-88',55.00,'WR',20)
INSERT INTO ASSIGNMENTS_KANZY(PROJID, EMPNO, A_END_DATE,A_START_DATE,BILL_RATE,ASSIGN_TYPE,HOURS)
VALUES(2,7844,'01-JAN-89','10-JAN-89',45.50,'PF',30)
--3. Cập nhật trường ASIGNMENT_TYPE từ WT thành WR\
UPDATE ASSIGNMENTS_KANZY e
set ASSIGN_TYPE = 'WT'
where e.ASSIGN_TYPE ='WR'
--4Nhập thêm số liệu vào bảng ASSIGNMENTS.
SELECT *FROM ASSIGNMENTS_KANZY
INSERT INTO ASSIGNMENTS_KANZY(PROJID, EMPNO, A_END_DATE,A_START_DATE,BILL_RATE,ASSIGN_TYPE,HOURS)
VALUES(1,7334,'05-DEC-78','03-DEC-78',50.00,'WR',14)
INSERT INTO ASSIGNMENTS_KANZY(PROJID, EMPNO, A_END_DATE,A_START_DATE,BILL_RATE,ASSIGN_TYPE,HOURS)
VALUES(1,7567,'04-JUL-88','07-JUL-88',13.00,'WR',21)
INSERT INTO ASSIGNMENTS_KANZY(PROJID, EMPNO, A_END_DATE,A_START_DATE,BILL_RATE,ASSIGN_TYPE,HOURS)
VALUES(2,7233,'10-MAY-89','1-MAY-89',44.50,'PF',27)
