--bai10
--bai1
--C1:
CREATE VIEW AGGREDATES_KANZY1 AS
SELECT *FROM AGGREDATES;
--C2:
CREATE OR REPLACE VIEW AGGREDATES_KANZY (DEPTNO, AVGSALARY, MAXIMUN, MINIMUN, SUM, NO_SALS,NO_COMMS )
AS
SELECT DEPTNO,ROUND(AVG(SAL),3), MAX(SAL), MIN(SAL), SUM(SAL), COUNT(*) , SUM(CASE WHEN COMM IS NULL THEN 0 WHEN COMM IS NOT NULL THEN 1 END)
FROM EMP
GROUP BY deptno;
--BAI2. Tạo view để nhập số liệu vào bảng ASIGNMENT với các điều kiện sau:
-- PROJID <2000, P_START_DATE<P_END_DATE
-- Các giá trị có thể chấp nhận của assign_type là PS, WT hoặc ED
-- EMPNO có giá trị NOT NULL
-- BILL_RATE < 50 Với ASSIGN_TYPE Là PS
-- BILL_RATE < 60 Với ASSIGN_TYPE Là WT
-- BILL_RATE < 70 Với ASSIGN_TYPE Là ED
CREATE VIEW VIEW_ASSIGNMENTS_KANZY AS SELECT *FROM ASSIGNMENTS_KANZY
WHERE "PROJID"<2 AND "A_START_DATE"<"A_END_DATE"
WITH CHECK OPTION; --THOẢ MÃN CÁC ĐIỀU KIỆN TRONG VIEW
--BAI3.Định nghĩa bảng MESSAGES có cấu trúc Column name Data Type
CREATE TABLE MESSAGES_KANZY(NUMCOL1 NUMBER (9,2),
NUMBCOL2 NUMBER(9,2),
CHARCOL1 VARCHAR2(60),
CHARCOL2 VARCHAR2(60),
DATECOL1 DATE,
DATECOL2 DATE
);
SELECT *FROM MESSAGES_KANZY;




